"""Official auth/model-list ONLY. There is deliberately no thread/turn inference path.

All login processes are newly created, per owner/connection, with clean child env.
Auth files belong solely to these fresh runtimes and are encrypted on archival.
No code here opens a host Codex account or takes external ChatGPT tokens.
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import queue
import re
import shutil
import stat
import subprocess
import tempfile
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import urlsplit
from uuid import UUID

from cryptography.fernet import Fernet, InvalidToken

from .codex_bridge_config import CodexBridgeConfig
from .providers import ProviderError

INFERENCE_BLOCK = "CODEX_TEXT_ISOLATION_UNVERIFIED"
VERIFIED_VERSION = "codex-cli 0.153.0"
AUTH_METHODS = frozenset({"initialize", "account/login/start", "account/read",
    "account/login/cancel", "account/logout", "model/list"})
SAFE_CONFIG = '''cli_auth_credentials_store = "file"
forced_login_method = "chatgpt"
project_doc_max_bytes = 0
web_search = "disabled"
approval_policy = "never"
[features]
shell_tool = false
unified_exec = false
apps = false
hooks = false
memories = false
remote_plugin = false
[features.code_mode]
enabled = false
[agents]
enabled = false
[apps._default]
enabled = false
[analytics]
enabled = false
'''


def capabilities(bridge=None):
    reason = bridge.unavailable_reason if bridge else "CODEX_BRIDGE_DISABLED"
    inference = reason is None and getattr(bridge, "text_engine", None) is not None
    return {"auth": reason is None, "model_list": reason is None, "inference": inference,
        "auth_blocked_reason": reason, "inference_blocked_reason": None if inference else INFERENCE_BLOCK,
        "browser_callback_reachable": bool(bridge and bridge.config.browser_callback_reachable),
        "live_verified": False}


def _private_directory(path, *, create=False):
    path = Path(path)
    if not path.is_absolute() or path != Path(os.path.abspath(path)):
        raise ProviderError("CODEX_STORAGE_PATH_UNSAFE")
    for part in (path, *path.parents):
        if part.is_symlink():
            raise ProviderError("CODEX_STORAGE_PATH_UNSAFE")
    if create:
        path.mkdir(mode=0o700, parents=True, exist_ok=True)
    info = path.stat()
    if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid() or stat.S_IMODE(info.st_mode) != 0o700:
        raise ProviderError("CODEX_STORAGE_PERMISSIONS")
    return path


def _read_private(path, limit):
    fd = os.open(path, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0))
    with os.fdopen(fd, "rb") as stream:
        info = os.fstat(stream.fileno())
        if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid() \
            or stat.S_IMODE(info.st_mode) != 0o600 or info.st_nlink != 1 or info.st_size > limit:
            raise ProviderError("CODEX_STORAGE_PERMISSIONS")
        return stream.read(limit + 1)


def _write_private(path, data):
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0), 0o600)
    with os.fdopen(fd, "wb") as stream:
        stream.write(data)
        stream.flush()
        os.fsync(stream.fileno())


def official_login_url(value, *, device=False):
    if not isinstance(value, str) or len(value) > 16384 or re.search(r"[\s\\\x00-\x1f]", value):
        raise ProviderError("CODEX_LOGIN_URL_INVALID")
    try:
        p = urlsplit(value)
        port = p.port
    except ValueError:
        raise ProviderError("CODEX_LOGIN_URL_INVALID") from None
    if p.scheme != "https" or p.hostname not in {"auth.openai.com", "chatgpt.com", "auth0.openai.com"} \
        or p.username or p.password or port not in (None, 443) or p.fragment:
        raise ProviderError("CODEX_LOGIN_URL_INVALID")
    if device and (p.hostname != "auth.openai.com" or p.path != "/codex/device" or p.query):
        raise ProviderError("CODEX_LOGIN_URL_INVALID")
    return value


class EncryptedAuthStore:
    """Only reads exact files generated by this instance or its bound encrypted archives."""
    def __init__(self, config, master_key):
        self.config = config
        try:
            self.cipher = Fernet(master_key.encode() if isinstance(master_key, str) else master_key)
        except (ValueError, TypeError):
            raise ProviderError("CODEX_CREDENTIAL_STORE_UNAVAILABLE") from None
        self.runtimes = {}
        self.root = self._root(config.runtime_root)
        self.archive = self._root(config.archive_root)
        if self.root == self.archive or self.root in self.archive.parents or self.archive in self.root.parents:
            raise ProviderError("CODEX_STORAGE_PATH_UNSAFE")

    def _root(self, path):
        if path is None:
            raise ProviderError("CODEX_CREDENTIAL_STORE_UNAVAILABLE")
        path = Path(path)
        project = Path(__file__).resolve().parents[2]
        denied = (project, Path.home() / ".codex", *self.config.forbidden_roots)
        if not path.is_absolute() or path in {Path("/"), Path.home(), Path("/tmp"), Path("/private/tmp")}:
            raise ProviderError("CODEX_STORAGE_PATH_UNSAFE")
        # Resolve aliases for comparison only; no credential/file content read.
        resolved = path.resolve()
        if any(resolved == p.resolve() or p.resolve() in resolved.parents or resolved in p.resolve().parents for p in denied):
            raise ProviderError("CODEX_STORAGE_PATH_UNSAFE")
        return _private_directory(path, create=True)

    def _identity(self, owner, connection):
        try:
            return str(UUID(owner)) + "." + str(UUID(connection))
        except (ValueError, TypeError, AttributeError):
            raise ProviderError("CODEX_IDENTITY_INVALID") from None

    def materialize(self, owner, connection, epoch, *, restore=False, config_text=SAFE_CONFIG):
        identity = self._identity(owner, connection)
        _private_directory(self.root)
        path = Path(tempfile.mkdtemp(prefix="identity-", dir=self.root))
        self.runtimes[path] = (owner, connection, epoch)
        _write_private(path / "config.toml", config_text.encode())
        _private_directory(path / "workspace", create=True)
        if restore:
            try:
                encrypted = _read_private(self.archive / (identity + ".enc"), 524288)
                payload = json.loads(self.cipher.decrypt(encrypted))
                if [payload.get(k) for k in ("owner", "connection", "epoch")] != [owner, connection, epoch]:
                    raise ProviderError("CODEX_AUTH_BINDING_INVALID")
                auth = base64.b64decode(payload["auth"], validate=True)
                if not 1 <= len(auth) <= 131072:
                    raise ValueError()
                _write_private(path / "auth.json", auth)
            except (OSError, InvalidToken, ValueError, KeyError, TypeError):
                self.release(path)
                raise ProviderError("CODEX_AUTH_ARCHIVE_UNAVAILABLE") from None
            except ProviderError:
                self.release(path)
                raise
        return path

    def persist(self, path):
        if path not in self.runtimes:
            raise ProviderError("CODEX_STORAGE_PATH_UNSAFE")
        _private_directory(path)
        owner, connection, epoch = self.runtimes[path]
        try:
            auth = _read_private(path / "auth.json", 131072)
        except OSError:
            raise ProviderError("CODEX_AUTH_NOT_PERSISTED") from None
        payload = {"owner": owner, "connection": connection, "epoch": epoch,
            "auth": base64.b64encode(auth).decode()}
        encrypted = self.cipher.encrypt(json.dumps(payload).encode())
        _private_directory(self.archive)
        target = self.archive / (self._identity(owner, connection) + ".enc")
        temporary = self.archive / (self._identity(owner, connection) + "." + os.urandom(8).hex() + ".tmp")
        _write_private(temporary, encrypted)
        os.replace(temporary, target)

    def forget(self, owner, connection):
        _private_directory(self.archive)
        path = self.archive / (self._identity(owner, connection) + ".enc")
        if path.is_symlink():
            raise ProviderError("CODEX_STORAGE_PATH_UNSAFE")
        path.unlink(missing_ok=True)

    def release(self, path):
        if path not in self.runtimes or path.parent != self.root:
            raise ProviderError("CODEX_STORAGE_PATH_UNSAFE")
        _private_directory(path)
        # This is an instance-created, registered, exact temporary identity only.
        shutil.rmtree(path)
        self.runtimes.pop(path, None)


class AuthStdioTransport:
    """No shell, proxy-to-host-daemon, websocket, generic RPC or model turns."""
    METHODS = AUTH_METHODS
    EVENT_METHODS = frozenset({"account/login/completed", "account/updated"})
    NOTIFICATION_OPT_OUT = ()
    def __init__(self, config, home):
        self.config = config
        self.responses = queue.Queue(maxsize=128)
        self.events = queue.Queue(maxsize=128)
        self.lock = threading.Lock()
        self.counter = 0
        self.failed = False
        self.failure_code = None
        exe = Path(config.executable)
        if not exe.is_absolute() or exe.is_symlink() or not exe.is_file():
            raise ProviderError("CODEX_EXECUTABLE_UNAVAILABLE")
        if config.executable_sha256 and hashlib.sha256(exe.read_bytes()).hexdigest() != config.executable_sha256:
            raise ProviderError("CODEX_VERSION_UNSUPPORTED")
        child_env = {"PATH": "/usr/bin:/bin:/usr/sbin:/sbin", "CODEX_HOME": str(home),
            "TMPDIR": str(home / "tmp"), "LANG": "en_US.UTF-8"}
        _private_directory(home / "tmp", create=True)
        version = subprocess.run([str(exe), "--version"], env=child_env, cwd=home / "workspace",
            capture_output=True, timeout=5, check=False)
        if version.returncode or version.stdout.decode(errors="replace").strip() != VERIFIED_VERSION:
            raise ProviderError("CODEX_VERSION_UNSUPPORTED")
        self.process = subprocess.Popen([str(exe), "app-server", "--strict-config", "--listen", "stdio://"],
            env=child_env, cwd=home / "workspace", stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL, start_new_session=True)
        self.reader = threading.Thread(target=self._read, daemon=True, name="fkb-codex-auth-rpc")
        self.reader.start()
        try:
            capabilities = {"experimentalApi": False}
            if self.NOTIFICATION_OPT_OUT:
                capabilities["optOutNotificationMethods"] = list(self.NOTIFICATION_OPT_OUT)
            self.call("initialize", {"clientInfo": {"name": "fund_knowledge_platform",
                "title": "基金运营知识平台", "version": "6.0.0"}, "capabilities": capabilities})
            self._write({"method": "initialized", "params": {}})
        except Exception:
            self.close()
            raise

    def _write(self, value):
        raw = json.dumps(value, separators=(",", ":")).encode() + b"\n"
        if len(raw) > self.config.max_rpc_bytes:
            raise ProviderError("CODEX_RPC_TOO_LARGE")
        try:
            self.process.stdin.write(raw)
            self.process.stdin.flush()
        except (OSError, ValueError):
            raise ProviderError("CODEX_RPC_UNAVAILABLE") from None

    def _enqueue_event(self, value):
        self.events.put_nowait(value)

    def _read(self):
        try:
            while True:
                raw = self.process.stdout.readline(self.config.max_rpc_bytes + 1)
                if not raw:
                    self.failure_code = "CODEX_RPC_CLOSED"
                    break
                if len(raw) > self.config.max_rpc_bytes:
                    self.failure_code = "CODEX_RPC_TOO_LARGE"
                    break
                value = json.loads(raw)
                if not isinstance(value, dict):
                    self.failure_code = "CODEX_RPC_INVALID_MESSAGE"
                    break
                if "method" in value and "id" in value:
                    # An auth-only session must never request execution/approval.
                    self._write({"id": value["id"], "error": {"code": -32601, "message": "Disabled"}})
                    self.failure_code = "CODEX_RPC_UNSOLICITED_REQUEST"
                    break
                if "id" in value:
                    self.responses.put_nowait(value)
                elif value.get("method") in self.EVENT_METHODS:
                    self._enqueue_event(value)
        except queue.Full:
            self.failure_code = "CODEX_RPC_BACKPRESSURE"
        except OSError:
            self.failure_code = "CODEX_RPC_IO_ERROR"
        except ValueError:
            self.failure_code = "CODEX_RPC_INVALID_MESSAGE"
        except ProviderError as exc:
            self.failure_code = exc.code if exc.code in {"CODEX_RPC_BACKPRESSURE", "CODEX_RPC_CLOSED", "CODEX_RPC_TOO_LARGE"} else "CODEX_RPC_UNAVAILABLE"
        finally:
            self.failed = True
            # Wake an in-flight caller immediately when the process exits;
            # never expose stderr (which can include identity information).
            try:
                self.responses.put_nowait({"transport_closed": True})
            except queue.Full:
                pass
            # Rejection alone does not end the process; close on every protocol
            # violation/EOF, including unsolicited execution requests.
            self.close()

    def call(self, method, params=None):
        if method not in self.METHODS or (method == "account/login/start" and params not in (
            {"type": "chatgptDeviceCode"}, {"type": "chatgpt"}
        )):
            raise ProviderError("CODEX_RPC_FORBIDDEN")
        with self.lock:
            if self.failed:
                raise ProviderError(getattr(self, "failure_code", None) or "CODEX_RPC_UNAVAILABLE")
            self.counter += 1
            self._write({"id": self.counter, "method": method, "params": params or {}})
            try:
                response = self.responses.get(timeout=self.config.rpc_timeout_seconds)
            except queue.Empty:
                self.close()
                raise ProviderError("CODEX_RPC_TIMEOUT") from None
            if response.get("transport_closed"):
                raise ProviderError(getattr(self, "failure_code", None) or "CODEX_RPC_UNAVAILABLE")
            if response.get("id") != self.counter or "error" in response or not isinstance(response.get("result"), dict):
                raise ProviderError("CODEX_RPC_FAILED")
            return response["result"]

    def notifications(self):
        events = []
        while not self.events.empty():
            events.append(self.events.get_nowait())
        return events

    def close(self):
        self.failed = True
        if self.process.poll() is None:
            self.process.terminate()
            try:
                self.process.wait(timeout=2)
            except subprocess.TimeoutExpired:
                self.process.kill()
                self.process.wait(timeout=2)
        for stream in (self.process.stdin, self.process.stdout):
            if stream:
                stream.close()


@dataclass
class LoginSession:
    home: Path
    rpc: object = field(repr=False)
    epoch: int = 0
    revision: int = 0
    attempt: str | None = None
    login_id: str | None = field(default=None, repr=False)
    challenge: dict | None = field(default=None, repr=False)
    expires: float = 0
    completed: bool = False
    authenticated: bool = False


class CodexBridge:
    def __init__(self, config=None, *, store=None, transport_factory=AuthStdioTransport):
        self.config = config or CodexBridgeConfig()
        self.store = store
        self.transport_factory = transport_factory
        self.sessions = {}
        self.locks = {}
        self.guard = threading.RLock()

    @property
    def unavailable_reason(self):
        if not self.config.enabled:
            return "CODEX_BRIDGE_DISABLED"
        if self.store is None:
            return "CODEX_CREDENTIAL_STORE_UNAVAILABLE"
        if self.transport_factory is AuthStdioTransport:
            if not self.config.auth_runtime_verified:
                return "CODEX_AUTH_RUNTIME_UNVERIFIED"
            if self.config.expected_version != VERIFIED_VERSION or not re.fullmatch(r"[a-f0-9]{64}", self.config.executable_sha256):
                return "CODEX_VERSION_UNSUPPORTED"
            if not self.config.executable or not Path(self.config.executable).is_file() or Path(self.config.executable).is_symlink():
                return "CODEX_EXECUTABLE_UNAVAILABLE"
            try:
                if hashlib.sha256(Path(self.config.executable).read_bytes()).hexdigest() != self.config.executable_sha256:
                    return "CODEX_VERSION_UNSUPPORTED"
            except OSError:
                return "CODEX_EXECUTABLE_UNAVAILABLE"
        return None

    def _lock(self, owner, connection):
        with self.guard:
            return self.locks.setdefault((owner, connection), threading.RLock())

    def _session(self, owner, connection, epoch, revision):
        session = self.sessions.get((owner, connection))
        if not session or session.epoch != epoch or session.revision != revision:
            raise ProviderError("CODEX_LOGIN_STALE")
        return session

    def start(self, owner, connection, epoch, revision, attempt, flow):
        if self.unavailable_reason:
            raise ProviderError(self.unavailable_reason)
        if flow not in {"device_code", "browser"} or (flow == "browser" and not self.config.browser_callback_reachable):
            raise ProviderError("CODEX_BROWSER_CALLBACK_UNAVAILABLE")
        with self._lock(owner, connection):
            if (owner, connection) in self.sessions:
                self.discard(owner, connection)
            home = self.store.materialize(owner, connection, epoch)
            try:
                rpc = self.transport_factory(self.config, home)
            except Exception:
                self.store.release(home)
                raise
            session = LoginSession(home, rpc, epoch, revision, attempt,
                expires=time.time() + self.config.login_ttl_seconds)
            self.sessions[owner, connection] = session
            try:
                # Fresh identity must be signed out, including after config layering.
                if rpc.call("account/read", {"refreshToken": False}).get("account") is not None:
                    raise ProviderError("CODEX_FRESH_IDENTITY_NOT_EMPTY")
                result = rpc.call("account/login/start", {"type": "chatgptDeviceCode" if flow == "device_code" else "chatgpt"})
                login_id = result.get("loginId")
                if not isinstance(login_id, str) or not 1 <= len(login_id) <= 128:
                    raise ProviderError("CODEX_LOGIN_RESPONSE_INVALID")
                challenge = {"attempt_id": attempt, "flow": flow, "verification_url": None,
                    "authorization_url": None, "user_code": None,
                    "local_expires_at": session.expires}
                if flow == "device_code":
                    challenge["verification_url"] = official_login_url(result.get("verificationUrl"), device=True)
                    code = result.get("userCode")
                    if not isinstance(code, str) or not re.fullmatch(r"[A-Za-z0-9-]{4,32}", code):
                        raise ProviderError("CODEX_LOGIN_RESPONSE_INVALID")
                    challenge["user_code"] = code
                else:
                    challenge["authorization_url"] = official_login_url(result.get("authUrl"))
                session.login_id, session.challenge = login_id, challenge
                return {"state": "PENDING", "account": None}
            except Exception:
                self.discard(owner, connection)
                raise

    def challenge(self, owner, connection, epoch, revision, attempt):
        with self._lock(owner, connection):
            session = self._session(owner, connection, epoch, revision)
            if session.attempt != attempt or not session.challenge or session.authenticated or time.time() >= session.expires:
                raise ProviderError("CODEX_LOGIN_STALE")
            return dict(session.challenge)

    def refresh(self, owner, connection, epoch, revision):
        with self._lock(owner, connection):
            previous = self.sessions.get((owner, connection))
            if previous and previous.epoch == epoch and previous.revision != revision and previous.authenticated:
                # Explicitly authorized application-consent revision. Restore
                # the same bound archive; never change identity or epoch.
                previous.rpc.close()
                self.store.release(previous.home)
                self.sessions.pop((owner, connection), None)
            if (owner, connection) not in self.sessions:
                # Explicit refresh can restore only this app's bound encrypted
                # archive, never a host account. GET remains non-mutating.
                if not isinstance(self.store, EncryptedAuthStore):
                    raise ProviderError("CODEX_LOGIN_STALE")
                home = self.store.materialize(owner, connection, epoch, restore=True)
                try:
                    rpc = self.transport_factory(self.config, home)
                except Exception:
                    self.store.release(home)
                    raise
                self.sessions[owner, connection] = LoginSession(home, rpc, epoch, revision,
                    completed=True, authenticated=True)
            session = self._session(owner, connection, epoch, revision)
            if not session.authenticated and time.time() >= session.expires:
                self.discard(owner, connection)
                return {"state": "EXPIRED", "account": None}
            for event in session.rpc.notifications():
                p = event.get("params", {})
                if event.get("method") == "account/login/completed" and p.get("loginId") == session.login_id:
                    if p.get("success") is not True:
                        self.discard(owner, connection)
                        raise ProviderError("CODEX_LOGIN_FAILED")
                    session.completed = True
            if not session.completed and not session.authenticated:
                return {"state": "PENDING", "account": None}
            account = session.rpc.call("account/read", {"refreshToken": False}).get("account")
            if not isinstance(account, dict) or account.get("type") != "chatgpt":
                self.discard(owner, connection)
                return {"state": "SIGNED_OUT", "account": None}
            if not session.authenticated:
                self.store.persist(session.home)
            session.authenticated, session.challenge = True, None
            plan = account.get("planType")
            return {"state": "AUTHENTICATED", "account": {"type": "chatgpt",
                "plan_type": plan if plan in {"free", "plus", "pro", "team", "business", "enterprise", "edu", "unknown"} else None}}

    def logout(self, owner, connection):
        with self._lock(owner, connection):
            session = self.sessions.get((owner, connection))
            try:
                if session:
                    session.rpc.call("account/logout", {})
                    if session.rpc.call("account/read", {"refreshToken": False}).get("account") is not None:
                        raise ProviderError("CODEX_LOGOUT_UNCONFIRMED")
            finally:
                self.discard(owner, connection)
            return {"state": "SIGNED_OUT", "account": None}

    def cancel(self, owner, connection):
        with self._lock(owner, connection):
            session = self.sessions.get((owner, connection))
            try:
                if session and session.login_id:
                    session.rpc.call("account/login/cancel", {"loginId": session.login_id})
                    # Even a late success cannot leave an authenticated process behind.
                    session.rpc.call("account/logout", {})
            finally:
                self.discard(owner, connection)
            return {"state": "CANCELLED", "account": None}

    def list_models(self, owner, connection, epoch, revision):
        with self._lock(owner, connection):
            session = self._session(owner, connection, epoch, revision)
            if not session.authenticated:
                raise ProviderError("CODEX_AUTH_REQUIRED")
            models, cursor, seen = [], None, set()
            for _ in range(10):
                params = {"includeHidden": False, "limit": min(100, self.config.max_models)}
                if cursor:
                    params["cursor"] = cursor
                result = session.rpc.call("model/list", params)
                if not isinstance(result.get("data"), list):
                    raise ProviderError("CODEX_MODELS_INVALID")
                for item in result["data"]:
                    model = item.get("model") or item.get("id")
                    if not isinstance(model, str) or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._:/+@-]{0,511}", model):
                        raise ProviderError("CODEX_MODELS_INVALID")
                    if item.get("hidden") or "text" not in item.get("inputModalities", ["text"]):
                        continue
                    if model not in {m["id"] for m in models}:
                        models.append({"id": model, "name": str(item.get("displayName") or model)[:300],
                            "brand": "openai", "source": "synced"})
                    if len(models) >= self.config.max_models:
                        return models, True
                cursor = result.get("nextCursor")
                if cursor is None:
                    return models, False
                if not isinstance(cursor, str) or len(cursor) > 2048 or cursor in seen:
                    raise ProviderError("CODEX_MODELS_INVALID")
                seen.add(cursor)
            return models, True

    def discard(self, owner, connection):
        with self._lock(owner, connection):
            session = self.sessions.pop((owner, connection), None)
            if session:
                try:
                    session.rpc.close()
                finally:
                    self.store.release(session.home)
            if self.store:
                self.store.forget(owner, connection)

    def discard_epoch(self, owner, connection, epoch):
        with self._lock(owner, connection):
            session = self.sessions.get((owner, connection))
            if session and session.epoch == epoch:
                self.discard(owner, connection)

    def close(self):
        for owner, connection in list(self.sessions):
            with self._lock(owner, connection):
                session = self.sessions.get((owner, connection))
                if session and session.authenticated:
                    # Preserve encrypted app-owned identity across normal host
                    # reloads. Explicit logout/discard still deletes it.
                    try:
                        archive = self.store.archive / (self.store._identity(owner, connection) + ".enc") if isinstance(self.store, EncryptedAuthStore) else None
                        if archive is None or not archive.exists():
                            self.store.persist(session.home)
                    finally:
                        session.rpc.close()
                        self.store.release(session.home)
                        self.sessions.pop((owner, connection), None)
                else:
                    self.discard(owner, connection)
